/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCashRouteImport } from './routes/_app/cash'
import { Route as AppCashflowRouteImport } from './routes/_app/cashflow'
import { Route as AppCopilotRouteImport } from './routes/_app/copilot'
import { Route as AppDebtsRouteImport } from './routes/_app/debts'
import { Route as AppFixedCostsRouteImport } from './routes/_app/fixed-costs'
import { Route as AppHrKoernerRouteImport } from './routes/_app/hr-koerner'
import { Route as AppInvestmentPlanRouteImport } from './routes/_app/investment-plan'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppNetWorthRouteImport } from './routes/_app/net-worth'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppRecapRouteImport } from './routes/_app/recap'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountsIdRouteImport } from './routes/_app/accounts/$id'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppAssetsIdRouteImport } from './routes/_app/assets/$id'
import { Route as AppConnectionsIndexRouteImport } from './routes/_app/connections/index'
import { Route as AppContractsIndexRouteImport } from './routes/_app/contracts/index'
import { Route as AppDepotsIdRouteImport } from './routes/_app/depots/$id'
import { Route as AppImportsIndexRouteImport } from './routes/_app/imports/index'
import { Route as AppLiabilitiesIndexRouteImport } from './routes/_app/liabilities/index'
import { Route as AppOptimizationsIndexRouteImport } from './routes/_app/optimizations/index'
import { Route as AppReceivablesIndexRouteImport } from './routes/_app/receivables/index'
import { Route as AppRecurringIndexRouteImport } from './routes/_app/recurring/index'
import { Route as AppSettingsDataSourcesRouteImport } from './routes/_app/settings_.data-sources'
import { Route as AppSettingsHrKoernerRouteImport } from './routes/_app/settings_.hr-koerner'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCopilotAttachmentsRouteImport } from './routes/api/copilot/attachments'
import { Route as ApiCopilotStreamRouteImport } from './routes/api/copilot/stream'
import { Route as ApiExportKindRouteImport } from './routes/api/export.$kind'
import { Route as ApiIntegrationsKatasterRouteImport } from './routes/api/integrations/kataster'
import { Route as ApiProviderCredentialsEnableBankingRouteImport } from './routes/api/provider-credentials/enable-banking'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiBankEnableBankingCallbackRouteImport } from './routes/api/bank/enable-banking/callback'
import { Route as ApiContractsDocumentsIdRouteImport } from './routes/api/contracts/documents/$id'
import { Route as ApiIntegrationsRemiseCallbackRouteImport } from './routes/api/integrations/remise/callback'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCashRoute = AppCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppFixedCostsRoute = AppFixedCostsRouteImport.update({
  id: '/fixed-costs',
  path: '/fixed-costs',
  getParentRoute: () => AppRoute,
} as any)
const AppHrKoernerRoute = AppHrKoernerRouteImport.update({
  id: '/hr-koerner',
  path: '/hr-koerner',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentPlanRoute = AppInvestmentPlanRouteImport.update({
  id: '/investment-plan',
  path: '/investment-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppNetWorthRoute = AppNetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppRecapRoute = AppRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIdRoute = AppAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsIndexRoute = AppConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsIndexRoute = AppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepotsIdRoute = AppDepotsIdRouteImport.update({
  id: '/depots/$id',
  path: '/depots/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsIndexRoute = AppImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => AppRoute,
} as any)
const AppLiabilitiesIndexRoute = AppLiabilitiesIndexRouteImport.update({
  id: '/liabilities/',
  path: '/liabilities/',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizationsIndexRoute = AppOptimizationsIndexRouteImport.update({
  id: '/optimizations/',
  path: '/optimizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesIndexRoute = AppReceivablesIndexRouteImport.update({
  id: '/receivables/',
  path: '/receivables/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringIndexRoute = AppRecurringIndexRouteImport.update({
  id: '/recurring/',
  path: '/recurring/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDataSourcesRoute = AppSettingsDataSourcesRouteImport.update({
  id: '/settings_/data-sources',
  path: '/settings/data-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsHrKoernerRoute = AppSettingsHrKoernerRouteImport.update({
  id: '/settings_/hr-koerner',
  path: '/settings/hr-koerner',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotAttachmentsRoute = ApiCopilotAttachmentsRouteImport.update({
  id: '/api/copilot/attachments',
  path: '/api/copilot/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotStreamRoute = ApiCopilotStreamRouteImport.update({
  id: '/api/copilot/stream',
  path: '/api/copilot/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportKindRoute = ApiExportKindRouteImport.update({
  id: '/api/export/$kind',
  path: '/api/export/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsKatasterRoute = ApiIntegrationsKatasterRouteImport.update({
  id: '/api/integrations/kataster',
  path: '/api/integrations/kataster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProviderCredentialsEnableBankingRoute =
  ApiProviderCredentialsEnableBankingRouteImport.update({
    id: '/api/provider-credentials/enable-banking',
    path: '/api/provider-credentials/enable-banking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBankEnableBankingCallbackRoute =
  ApiBankEnableBankingCallbackRouteImport.update({
    id: '/api/bank/enable-banking/callback',
    path: '/api/bank/enable-banking/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiContractsDocumentsIdRoute = ApiContractsDocumentsIdRouteImport.update({
  id: '/api/contracts/documents/$id',
  path: '/api/contracts/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsRemiseCallbackRoute =
  ApiIntegrationsRemiseCallbackRouteImport.update({
    id: '/api/integrations/remise/callback',
    path: '/api/integrations/remise/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cash': typeof AppCashRoute
  '/cashflow': typeof AppCashflowRoute
  '/copilot': typeof AppCopilotRoute
  '/debts': typeof AppDebtsRoute
  '/fixed-costs': typeof AppFixedCostsRoute
  '/hr-koerner': typeof AppHrKoernerRoute
  '/investment-plan': typeof AppInvestmentPlanRoute
  '/investments': typeof AppInvestmentsRoute
  '/net-worth': typeof AppNetWorthRoute
  '/overview': typeof AppOverviewRoute
  '/recap': typeof AppRecapRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/assets/$id': typeof AppAssetsIdRoute
  '/depots/$id': typeof AppDepotsIdRoute
  '/settings/data-sources': typeof AppSettingsDataSourcesRoute
  '/settings/hr-koerner': typeof AppSettingsHrKoernerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/copilot/attachments': typeof ApiCopilotAttachmentsRoute
  '/api/copilot/stream': typeof ApiCopilotStreamRoute
  '/api/export/$kind': typeof ApiExportKindRoute
  '/api/integrations/kataster': typeof ApiIntegrationsKatasterRoute
  '/api/provider-credentials/enable-banking': typeof ApiProviderCredentialsEnableBankingRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/connections/': typeof AppConnectionsIndexRoute
  '/contracts/': typeof AppContractsIndexRoute
  '/imports/': typeof AppImportsIndexRoute
  '/liabilities/': typeof AppLiabilitiesIndexRoute
  '/optimizations/': typeof AppOptimizationsIndexRoute
  '/receivables/': typeof AppReceivablesIndexRoute
  '/recurring/': typeof AppRecurringIndexRoute
  '/api/bank/enable-banking/callback': typeof ApiBankEnableBankingCallbackRoute
  '/api/contracts/documents/$id': typeof ApiContractsDocumentsIdRoute
  '/api/integrations/remise/callback': typeof ApiIntegrationsRemiseCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/cash': typeof AppCashRoute
  '/cashflow': typeof AppCashflowRoute
  '/copilot': typeof AppCopilotRoute
  '/debts': typeof AppDebtsRoute
  '/fixed-costs': typeof AppFixedCostsRoute
  '/hr-koerner': typeof AppHrKoernerRoute
  '/investment-plan': typeof AppInvestmentPlanRoute
  '/investments': typeof AppInvestmentsRoute
  '/net-worth': typeof AppNetWorthRoute
  '/overview': typeof AppOverviewRoute
  '/recap': typeof AppRecapRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/': typeof AppIndexRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/assets/$id': typeof AppAssetsIdRoute
  '/depots/$id': typeof AppDepotsIdRoute
  '/settings/data-sources': typeof AppSettingsDataSourcesRoute
  '/settings/hr-koerner': typeof AppSettingsHrKoernerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/copilot/attachments': typeof ApiCopilotAttachmentsRoute
  '/api/copilot/stream': typeof ApiCopilotStreamRoute
  '/api/export/$kind': typeof ApiExportKindRoute
  '/api/integrations/kataster': typeof ApiIntegrationsKatasterRoute
  '/api/provider-credentials/enable-banking': typeof ApiProviderCredentialsEnableBankingRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/assets': typeof AppAssetsIndexRoute
  '/connections': typeof AppConnectionsIndexRoute
  '/contracts': typeof AppContractsIndexRoute
  '/imports': typeof AppImportsIndexRoute
  '/liabilities': typeof AppLiabilitiesIndexRoute
  '/optimizations': typeof AppOptimizationsIndexRoute
  '/receivables': typeof AppReceivablesIndexRoute
  '/recurring': typeof AppRecurringIndexRoute
  '/api/bank/enable-banking/callback': typeof ApiBankEnableBankingCallbackRoute
  '/api/contracts/documents/$id': typeof ApiContractsDocumentsIdRoute
  '/api/integrations/remise/callback': typeof ApiIntegrationsRemiseCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/cash': typeof AppCashRoute
  '/_app/cashflow': typeof AppCashflowRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/debts': typeof AppDebtsRoute
  '/_app/fixed-costs': typeof AppFixedCostsRoute
  '/_app/hr-koerner': typeof AppHrKoernerRoute
  '/_app/investment-plan': typeof AppInvestmentPlanRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/net-worth': typeof AppNetWorthRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/recap': typeof AppRecapRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$id': typeof AppAccountsIdRoute
  '/_app/assets/$id': typeof AppAssetsIdRoute
  '/_app/depots/$id': typeof AppDepotsIdRoute
  '/_app/settings_/data-sources': typeof AppSettingsDataSourcesRoute
  '/_app/settings_/hr-koerner': typeof AppSettingsHrKoernerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/copilot/attachments': typeof ApiCopilotAttachmentsRoute
  '/api/copilot/stream': typeof ApiCopilotStreamRoute
  '/api/export/$kind': typeof ApiExportKindRoute
  '/api/integrations/kataster': typeof ApiIntegrationsKatasterRoute
  '/api/provider-credentials/enable-banking': typeof ApiProviderCredentialsEnableBankingRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/connections/': typeof AppConnectionsIndexRoute
  '/_app/contracts/': typeof AppContractsIndexRoute
  '/_app/imports/': typeof AppImportsIndexRoute
  '/_app/liabilities/': typeof AppLiabilitiesIndexRoute
  '/_app/optimizations/': typeof AppOptimizationsIndexRoute
  '/_app/receivables/': typeof AppReceivablesIndexRoute
  '/_app/recurring/': typeof AppRecurringIndexRoute
  '/api/bank/enable-banking/callback': typeof ApiBankEnableBankingCallbackRoute
  '/api/contracts/documents/$id': typeof ApiContractsDocumentsIdRoute
  '/api/integrations/remise/callback': typeof ApiIntegrationsRemiseCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/cash'
    | '/cashflow'
    | '/copilot'
    | '/debts'
    | '/fixed-costs'
    | '/hr-koerner'
    | '/investment-plan'
    | '/investments'
    | '/net-worth'
    | '/overview'
    | '/recap'
    | '/settings'
    | '/transactions'
    | '/api/health'
    | '/api/mcp'
    | '/accounts/$id'
    | '/assets/$id'
    | '/depots/$id'
    | '/settings/data-sources'
    | '/settings/hr-koerner'
    | '/api/auth/$'
    | '/api/copilot/attachments'
    | '/api/copilot/stream'
    | '/api/export/$kind'
    | '/api/integrations/kataster'
    | '/api/provider-credentials/enable-banking'
    | '/api/rpc/$'
    | '/accounts/'
    | '/assets/'
    | '/connections/'
    | '/contracts/'
    | '/imports/'
    | '/liabilities/'
    | '/optimizations/'
    | '/receivables/'
    | '/recurring/'
    | '/api/bank/enable-banking/callback'
    | '/api/contracts/documents/$id'
    | '/api/integrations/remise/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy'
    | '/terms'
    | '/cash'
    | '/cashflow'
    | '/copilot'
    | '/debts'
    | '/fixed-costs'
    | '/hr-koerner'
    | '/investment-plan'
    | '/investments'
    | '/net-worth'
    | '/overview'
    | '/recap'
    | '/settings'
    | '/transactions'
    | '/api/health'
    | '/api/mcp'
    | '/'
    | '/accounts/$id'
    | '/assets/$id'
    | '/depots/$id'
    | '/settings/data-sources'
    | '/settings/hr-koerner'
    | '/api/auth/$'
    | '/api/copilot/attachments'
    | '/api/copilot/stream'
    | '/api/export/$kind'
    | '/api/integrations/kataster'
    | '/api/provider-credentials/enable-banking'
    | '/api/rpc/$'
    | '/accounts'
    | '/assets'
    | '/connections'
    | '/contracts'
    | '/imports'
    | '/liabilities'
    | '/optimizations'
    | '/receivables'
    | '/recurring'
    | '/api/bank/enable-banking/callback'
    | '/api/contracts/documents/$id'
    | '/api/integrations/remise/callback'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_app/cash'
    | '/_app/cashflow'
    | '/_app/copilot'
    | '/_app/debts'
    | '/_app/fixed-costs'
    | '/_app/hr-koerner'
    | '/_app/investment-plan'
    | '/_app/investments'
    | '/_app/net-worth'
    | '/_app/overview'
    | '/_app/recap'
    | '/_app/settings'
    | '/_app/transactions'
    | '/api/health'
    | '/api/mcp'
    | '/_app/'
    | '/_app/accounts/$id'
    | '/_app/assets/$id'
    | '/_app/depots/$id'
    | '/_app/settings_/data-sources'
    | '/_app/settings_/hr-koerner'
    | '/api/auth/$'
    | '/api/copilot/attachments'
    | '/api/copilot/stream'
    | '/api/export/$kind'
    | '/api/integrations/kataster'
    | '/api/provider-credentials/enable-banking'
    | '/api/rpc/$'
    | '/_app/accounts/'
    | '/_app/assets/'
    | '/_app/connections/'
    | '/_app/contracts/'
    | '/_app/imports/'
    | '/_app/liabilities/'
    | '/_app/optimizations/'
    | '/_app/receivables/'
    | '/_app/recurring/'
    | '/api/bank/enable-banking/callback'
    | '/api/contracts/documents/$id'
    | '/api/integrations/remise/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCopilotAttachmentsRoute: typeof ApiCopilotAttachmentsRoute
  ApiCopilotStreamRoute: typeof ApiCopilotStreamRoute
  ApiExportKindRoute: typeof ApiExportKindRoute
  ApiIntegrationsKatasterRoute: typeof ApiIntegrationsKatasterRoute
  ApiProviderCredentialsEnableBankingRoute: typeof ApiProviderCredentialsEnableBankingRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiBankEnableBankingCallbackRoute: typeof ApiBankEnableBankingCallbackRoute
  ApiContractsDocumentsIdRoute: typeof ApiContractsDocumentsIdRoute
  ApiIntegrationsRemiseCallbackRoute: typeof ApiIntegrationsRemiseCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash': {
      id: '/_app/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AppCashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashflow': {
      id: '/_app/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debts': {
      id: '/_app/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fixed-costs': {
      id: '/_app/fixed-costs'
      path: '/fixed-costs'
      fullPath: '/fixed-costs'
      preLoaderRoute: typeof AppFixedCostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr-koerner': {
      id: '/_app/hr-koerner'
      path: '/hr-koerner'
      fullPath: '/hr-koerner'
      preLoaderRoute: typeof AppHrKoernerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investment-plan': {
      id: '/_app/investment-plan'
      path: '/investment-plan'
      fullPath: '/investment-plan'
      preLoaderRoute: typeof AppInvestmentPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/net-worth': {
      id: '/_app/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof AppNetWorthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recap': {
      id: '/_app/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof AppRecapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$id': {
      id: '/_app/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/$id': {
      id: '/_app/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AppAssetsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/': {
      id: '/_app/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AppConnectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/': {
      id: '/_app/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AppContractsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/depots/$id': {
      id: '/_app/depots/$id'
      path: '/depots/$id'
      fullPath: '/depots/$id'
      preLoaderRoute: typeof AppDepotsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imports/': {
      id: '/_app/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof AppImportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liabilities/': {
      id: '/_app/liabilities/'
      path: '/liabilities'
      fullPath: '/liabilities/'
      preLoaderRoute: typeof AppLiabilitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/optimizations/': {
      id: '/_app/optimizations/'
      path: '/optimizations'
      fullPath: '/optimizations/'
      preLoaderRoute: typeof AppOptimizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receivables/': {
      id: '/_app/receivables/'
      path: '/receivables'
      fullPath: '/receivables/'
      preLoaderRoute: typeof AppReceivablesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring/': {
      id: '/_app/recurring/'
      path: '/recurring'
      fullPath: '/recurring/'
      preLoaderRoute: typeof AppRecurringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/data-sources': {
      id: '/_app/settings_/data-sources'
      path: '/settings/data-sources'
      fullPath: '/settings/data-sources'
      preLoaderRoute: typeof AppSettingsDataSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/hr-koerner': {
      id: '/_app/settings_/hr-koerner'
      path: '/settings/hr-koerner'
      fullPath: '/settings/hr-koerner'
      preLoaderRoute: typeof AppSettingsHrKoernerRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/attachments': {
      id: '/api/copilot/attachments'
      path: '/api/copilot/attachments'
      fullPath: '/api/copilot/attachments'
      preLoaderRoute: typeof ApiCopilotAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/stream': {
      id: '/api/copilot/stream'
      path: '/api/copilot/stream'
      fullPath: '/api/copilot/stream'
      preLoaderRoute: typeof ApiCopilotStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/$kind': {
      id: '/api/export/$kind'
      path: '/api/export/$kind'
      fullPath: '/api/export/$kind'
      preLoaderRoute: typeof ApiExportKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/kataster': {
      id: '/api/integrations/kataster'
      path: '/api/integrations/kataster'
      fullPath: '/api/integrations/kataster'
      preLoaderRoute: typeof ApiIntegrationsKatasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provider-credentials/enable-banking': {
      id: '/api/provider-credentials/enable-banking'
      path: '/api/provider-credentials/enable-banking'
      fullPath: '/api/provider-credentials/enable-banking'
      preLoaderRoute: typeof ApiProviderCredentialsEnableBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bank/enable-banking/callback': {
      id: '/api/bank/enable-banking/callback'
      path: '/api/bank/enable-banking/callback'
      fullPath: '/api/bank/enable-banking/callback'
      preLoaderRoute: typeof ApiBankEnableBankingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contracts/documents/$id': {
      id: '/api/contracts/documents/$id'
      path: '/api/contracts/documents/$id'
      fullPath: '/api/contracts/documents/$id'
      preLoaderRoute: typeof ApiContractsDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/remise/callback': {
      id: '/api/integrations/remise/callback'
      path: '/api/integrations/remise/callback'
      fullPath: '/api/integrations/remise/callback'
      preLoaderRoute: typeof ApiIntegrationsRemiseCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCashRoute: typeof AppCashRoute
  AppCashflowRoute: typeof AppCashflowRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDebtsRoute: typeof AppDebtsRoute
  AppFixedCostsRoute: typeof AppFixedCostsRoute
  AppHrKoernerRoute: typeof AppHrKoernerRoute
  AppInvestmentPlanRoute: typeof AppInvestmentPlanRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppNetWorthRoute: typeof AppNetWorthRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppRecapRoute: typeof AppRecapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsIdRoute: typeof AppAccountsIdRoute
  AppAssetsIdRoute: typeof AppAssetsIdRoute
  AppDepotsIdRoute: typeof AppDepotsIdRoute
  AppSettingsDataSourcesRoute: typeof AppSettingsDataSourcesRoute
  AppSettingsHrKoernerRoute: typeof AppSettingsHrKoernerRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppConnectionsIndexRoute: typeof AppConnectionsIndexRoute
  AppContractsIndexRoute: typeof AppContractsIndexRoute
  AppImportsIndexRoute: typeof AppImportsIndexRoute
  AppLiabilitiesIndexRoute: typeof AppLiabilitiesIndexRoute
  AppOptimizationsIndexRoute: typeof AppOptimizationsIndexRoute
  AppReceivablesIndexRoute: typeof AppReceivablesIndexRoute
  AppRecurringIndexRoute: typeof AppRecurringIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCashRoute: AppCashRoute,
  AppCashflowRoute: AppCashflowRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDebtsRoute: AppDebtsRoute,
  AppFixedCostsRoute: AppFixedCostsRoute,
  AppHrKoernerRoute: AppHrKoernerRoute,
  AppInvestmentPlanRoute: AppInvestmentPlanRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppNetWorthRoute: AppNetWorthRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppRecapRoute: AppRecapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountsIdRoute: AppAccountsIdRoute,
  AppAssetsIdRoute: AppAssetsIdRoute,
  AppDepotsIdRoute: AppDepotsIdRoute,
  AppSettingsDataSourcesRoute: AppSettingsDataSourcesRoute,
  AppSettingsHrKoernerRoute: AppSettingsHrKoernerRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppConnectionsIndexRoute: AppConnectionsIndexRoute,
  AppContractsIndexRoute: AppContractsIndexRoute,
  AppImportsIndexRoute: AppImportsIndexRoute,
  AppLiabilitiesIndexRoute: AppLiabilitiesIndexRoute,
  AppOptimizationsIndexRoute: AppOptimizationsIndexRoute,
  AppReceivablesIndexRoute: AppReceivablesIndexRoute,
  AppRecurringIndexRoute: AppRecurringIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCopilotAttachmentsRoute: ApiCopilotAttachmentsRoute,
  ApiCopilotStreamRoute: ApiCopilotStreamRoute,
  ApiExportKindRoute: ApiExportKindRoute,
  ApiIntegrationsKatasterRoute: ApiIntegrationsKatasterRoute,
  ApiProviderCredentialsEnableBankingRoute:
    ApiProviderCredentialsEnableBankingRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiBankEnableBankingCallbackRoute: ApiBankEnableBankingCallbackRoute,
  ApiContractsDocumentsIdRoute: ApiContractsDocumentsIdRoute,
  ApiIntegrationsRemiseCallbackRoute: ApiIntegrationsRemiseCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
